// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Antd = require("antd");
var React = require("react");

function App(Props) {
  var greeting = Props.greeting;
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, greeting), React.createElement(Antd.Button, {
                  children: "Pretty Button",
                  type: "primary"
                }));
}

var make = App;

exports.make = make;
/* antd Not a pure module */
